[tool.poetry]
name = "meeting-scheduler"
version = "0.1.0"
description = ""
authors = ["Dia <kangdiamond@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
radicale = "^3.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
